version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installation des dépendances"
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Construction terminée"

  post_build:
    commands:
      - echo "Connexion SSH et déploiement"
      - PRIVATE_KEY=$(aws secretsmanager get-secret-value --secret-id EC2PrivateKey --query SecretString --output text)
      - echo "$PRIVATE_KEY" > key.pem
      - chmod 400 key.pem
      - ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@<EC2_PUBLIC_IP> "
          cd /home/ubuntu/myproject &&
          git pull &&
          source venv/bin/activate &&
          pip install -r requirements.txt &&
          python manage.py migrate &&
          sudo systemctl restart gunicorn
        "

artifacts:
  files:
    - '**/*'
