version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Install des dépendances…"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Tests / migrations / collectstatic…"
      - python manage.py migrate --no‑input
      - python manage.py collectstatic --no‑input

artifacts:
  files:
    - '**/*'
