# Generated by Django 5.0.1 on 2025-04-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_terrain_caracteristiques_terrain_disponible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrain',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
