# Generated by Django 5.0.1 on 2025-04-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_terrain_caracteristiques'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='image_url',
        ),
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipments/'),
        ),
    ]
