# Generated by Django 5.0.1 on 2025-04-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_equipment_image_url_equipment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='quantity',
        ),
    ]
