# Generated by Django 5.2 on 2025-05-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Carte bancaire'), ('cash', 'Espèces'), ('transfer', 'Virement')], default='card', max_length=20),
        ),
    ] 