# Generated by Django 5.0.1 on 2025-04-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='discipline',
            field=models.CharField(choices=[('FOOTBALL', 'Football'), ('BASKETBALL', 'Basketball'), ('TENNIS', 'Tennis'), ('VOLLEYBALL', 'Volleyball'), ('RUGBY', 'Rugby'), ('HANDBALL', 'Handball'), ('AUTRE', 'Autre')], default='FOOTBALL', max_length=20),
        ),
    ]
