# Generated by Django 5.0.1 on 2025-04-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_terrain_discipline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terrain",
            name="discipline",
            field=models.CharField(
                choices=[
                    ("FOOTBALL_11", "Football 11 vs 11"),
                    ("FOOTBALL_5", "Football 5 vs 5"),
                    ("FOOTBALL_6", "Football 6 vs 6"),
                    ("PADEL_2", "Padel 2 vs 2"),
                    ("BASKET_3", "Basket 3 vs 3"),
                ],
                default="FOOTBALL_11",
                max_length=20,
            ),
        ),
    ]
