# Generated by Django 5.2 on 2025-05-09 16:45

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro de téléphone doit être au format : 0612345678, 0712345678, 212612345678 ou 212712345678', regex='^(?:(?:\\+|00)212|0)[67]\\d{8}$')]),
        ),
    ] 