# Generated by Django 5.0.1 on 2025-05-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_customuser_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/'),
        ),
    ]
