# Generated by Django 5.2.1 on 2025-05-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_reservation_created_at_reservation_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='discipline',
            field=models.CharField(choices=[('padel', 'Padel'), ('basket', 'Basket'), ('tennis', 'Tennis'), ('football', 'Football'), ('volley', 'Volley'), ('handball', 'Handball'), ('badminton', 'Badminton'), ('squash', 'Squash'), ('multisport', 'Multisport')], default='padel', max_length=20),
        ),
    ]
