# Generated by Django 5.2.1 on 2025-05-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_club_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='club',
            name='discipline',
        ),
        migrations.AddField(
            model_name='club',
            name='disciplines',
            field=models.ManyToManyField(related_name='clubs', to='core.discipline'),
        ),
    ]
