# Generated by Django 5.2.1 on 2025-05-18 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_discipline_remove_club_discipline_club_disciplines'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='discipline_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terrains_temp', to='core.discipline'),
        ),
        migrations.AlterField(
            model_name='terrain',
            name='discipline',
            field=models.CharField(max_length=20),
        ),
    ]
